dist:
  module: github.com/Sinkinson/otel-collector-custom
  name: collector
  description: Custom OTel collector for testing
  output_path: "./otel-collector-custom"
  otelcol_version: "0.62.0"

receivers:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsfirehosereceiver v0.62.0"
  - import: go.opentelemetry.io/collector/receiver/otlpreceiver
    gomod: go.opentelemetry.io/collector v0.62.0

exporters:
  - gomod: "github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.62.0"
  - import: go.opentelemetry.io/collector/exporter/loggingexporter
    gomod: go.opentelemetry.io/collector v0.62.0
  - import: go.opentelemetry.io/collector/exporter/otlphttpexporter
    gomod: go.opentelemetry.io/collector v0.62.0

processors:
  - import: go.opentelemetry.io/collector/processor/batchprocessor
    gomod: go.opentelemetry.io/collector v0.62.0

replaces:
  - cloud.google.com/go => cloud.google.com/go v0.100.2
